[versions]
# Source
java = "17"
kotlin = "2.4.0"

# Required Libraries
netty = "4.2.15.Final"

# Tooling Libraries
javaPoet = "1.13.0"
argParser = "2.0.7"
asciidoctorJ = "2.5.10"

# Testing dependencies
junit = "6.1.0"
hamcrest = "2.2"
guava = "33.6.0-jre"
compilerTesting = "0.23.0"
checkstyle = "12.3.1"
testcontainers = "2.0.5"

# Plugin dependencies
shadowPlugin = "9.3.0"
asciiDoctorPlugin = "4.0.5"
gitPublishPlugin = "6.0.0"
testLoggerPlugin = "4.0.0"


# Other versions
downloadPlugin = "5.7.0"
versionsPlugin = "0.54.0"

[libraries]
# Required Libraries
netty-common = { group = "io.netty", name = "netty-common", version.ref = "netty" }
netty-buffer = { group = "io.netty", name = "netty-buffer", version.ref = "netty" }
netty-transport = { group = "io.netty", name = "netty-transport", version.ref = "netty" }
netty-codec = { group = "io.netty", name = "netty-codec", version.ref = "netty" }
netty-handler = { group = "io.netty", name = "netty-handler", version.ref = "netty" }
netty-transport-native-unix-common = { group = "io.netty", name = "netty-transport-native-unix-common", version.ref = "netty" }
netty-transport-native-kqueue = { group = "io.netty", name = "netty-transport-native-kqueue", version.ref = "netty" }
netty-transport-native-epoll = { group = "io.netty", name = "netty-transport-native-epoll", version.ref = "netty" }
jspecify = {group= "org.jspecify", name= "jspecify", version = "1.0.0"}

# Tooling Libraries
javapoet = { group = "com.squareup", name = "javapoet", version.ref = "javaPoet" }
kotlin-argparser = { group = "com.xenomachina", name = "kotlin-argparser", version.ref = "argParser" }
asciidoctorj = { group = "org.asciidoctor", name = "asciidoctorj", version.ref = "asciidoctorJ" }

# Testing dependencies
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit" }
junit-platform-suite-api = { group = "org.junit.platform", name = "junit-platform-suite-api", version.ref = "junit" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
compiler-testing = { group = "com.google.testing.compile", name = "compile-testing", version.ref = "compilerTesting" }
checkstyle = { group = "com.puppycrawl.tools", name = "checkstyle", version.ref = "checkstyle" }
testcontainers-jdbc = { group = "org.testcontainers", name = "testcontainers-jdbc", version.ref = "testcontainers" }
testcontainers-junit-jupiter = {group = "org.testcontainers", name = "testcontainers-junit-jupiter", version.ref = "testcontainers" }

# Specially for buildSrc
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
javaparser-core = { group = "com.github.javaparser", name = "javaparser-symbol-solver-core", version = "3.17.0" }

[plugins]
# Plugin dependencies
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadowPlugin" }
asciidoctor-convert = { id = "org.asciidoctor.jvm.convert", version.ref = "asciiDoctorPlugin" }
git-publish = { id = "org.ajoberstar.git-publish", version.ref = "gitPublishPlugin" }
test-logger = { id = "com.adarshr.test-logger", version.ref = "testLoggerPlugin" }

download = { id = "de.undercouch.download", version.ref = "downloadPlugin" }
benmanes-versions = { id = "com.github.ben-manes.versions", version.ref = "versionsPlugin" }

